/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JOptionPane;
import modelo.Sistema;
/**
 *
 * @author vince
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private Sistema modelo;
    
    public VentanaPrincipal(Sistema unModelo) {
        this.modelo = unModelo;
        initComponents();
        this.actualizarVentana();
    }
    
    public Sistema getModelo() {
        return this.modelo;
    }
    
    public void setModelo(Sistema unModelo) {
        this.modelo = unModelo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        barraMenu = new javax.swing.JMenuBar();
        menuPrograma = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuOpciones = new javax.swing.JMenu();
        menuFamilia = new javax.swing.JMenuItem();
        menuMascotas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        menuPrograma.setText("Calendario");

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuPrograma.add(jMenuItem2);

        barraMenu.add(menuPrograma);

        jMenu1.setText("Eventos");

        jMenuItem1.setText("Nuevo evento");
        jMenu1.add(jMenuItem1);

        barraMenu.add(jMenu1);

        menuOpciones.setText("Opciones");
        menuOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcionesActionPerformed(evt);
            }
        });

        menuFamilia.setText("Familia");
        menuFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFamiliaActionPerformed(evt);
            }
        });
        menuOpciones.add(menuFamilia);

        menuMascotas.setText("Mascotas");
        menuMascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMascotasActionPerformed(evt);
            }
        });
        menuOpciones.add(menuMascotas);

        barraMenu.add(menuOpciones);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcionesActionPerformed
        JOptionPane.showMessageDialog(this, "No se puede pasar el turno, toravia tiene movimientos disponibles", "Alerta", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_menuOpcionesActionPerformed

    private void menuFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFamiliaActionPerformed
        VentanaFamilia ventana = new VentanaFamilia(this.modelo);
        ventana.setVisible(true);
    }//GEN-LAST:event_menuFamiliaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMascotasActionPerformed
        VentanaMascotas ventana = new VentanaMascotas(this.getModelo());
        ventana.setVisible(true);
    }//GEN-LAST:event_menuMascotasActionPerformed

    private void actualizarVentana() {
        this.jList1.setListData(this.getModelo().getEventos().toArray());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuFamilia;
    private javax.swing.JMenuItem menuMascotas;
    private javax.swing.JMenu menuOpciones;
    private javax.swing.JMenu menuPrograma;
    // End of variables declaration//GEN-END:variables
}
