/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JOptionPane;
import modelo.Sistema;
/**
 *
 * @author vince
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private Sistema modelo;
    
    public VentanaPrincipal(Sistema unModelo) {
        this.modelo = unModelo;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        menuPrograma = new javax.swing.JMenu();
        menuOpciones = new javax.swing.JMenu();
        menuFamilia = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPrograma.setText("Programa");
        barraMenu.add(menuPrograma);

        menuOpciones.setText("Opciones");
        menuOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcionesActionPerformed(evt);
            }
        });

        menuFamilia.setText("Familia");
        menuFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFamiliaActionPerformed(evt);
            }
        });
        menuOpciones.add(menuFamilia);

        jMenuItem1.setText("jMenuItem1");
        menuOpciones.add(jMenuItem1);

        barraMenu.add(menuOpciones);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcionesActionPerformed
        JOptionPane.showMessageDialog(this, "No se puede pasar el turno, toravia tiene movimientos disponibles", "Alerta", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_menuOpcionesActionPerformed

    private void menuFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFamiliaActionPerformed
        VentanaFamilia ventana = new VentanaFamilia(this.modelo);
        ventana.setVisible(true);
    }//GEN-LAST:event_menuFamiliaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuFamilia;
    private javax.swing.JMenu menuOpciones;
    private javax.swing.JMenu menuPrograma;
    // End of variables declaration//GEN-END:variables
}
